[propaganda]
# shiny crowns
blink = false

[nuke]
# always ask for confirmation on jhack nuke
ask_for_confirmation = true
# have the bomb be blinky
blink = false
# nuke without --force --no-wait
gently = false

[tail]
# pop empty columns from tail output
remove_empty_columns = true
# bump loglevel to unit=TRACE before tailing, and pop it back to whatever it was before when tail exits
automatically_bump_loglevel = false
# setting this to higher numbers tends to break shift-selection in shells
refresh_per_second = 4

[general]
# Setting this to True enables 'destructive mode'.
# This will enable you to run all destructive commands without confirmation prompt.
# Only exception is nuke: to disable that one too, edit [nuke]ask_for_confirmation above.
# This mode is intended for development environments and should be disabled in production!
# This is *for your own good*.
# If you want to enable destructive mode on a per-command basis, you can
# set the envvar `JHACK_PROFILE=devmode` before running jhack.
enable_destructive_commands_NO_PRODUCTION_zero_guarantees = false